name: scrape_daily_solve_times
on:
  schedule:
    - cron: '59 1 * * 2-6'
    - cron: '59 21 * * 6'
    - cron: '59 21 * * SUN'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r pip_requirements/daily_scraper_requirements.txt

      - name: Execute Python script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          GOOGLE_API_CONFIG:  ${{ secrets.GOOGLE_API_CONFIG }}
        run: |
          python daily_scraper.py
