name: scrape_daily_solve_times

on:
  schedule:
    - cron: '59 1 * * 2-6'
    - cron: '59 21 * * 6'
    - cron: '59 21 * * SUN'
      
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
      - uses: actions/checkout@v2
        
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r daily_scraper_requirements.txt

      - name: Execute Python script
        run: |
          python daily_scraper.py
